ifndef::imagesdir[:imagesdir: ../images]

[[section-solution-strategy]]
== Solution Strategy

[role="arc42help"]
**
.Contents
A short summary and explanation of the fundamental decisions and solution strategies, that shape system architecture. It includes

* technology decisions
* decisions about the top-level decomposition of the system, e.g. usage of an architectural pattern or design pattern
* decisions on how to achieve key quality goals
* relevant organizational decisions, e.g. selecting a development process or delegating certain tasks to third parties.

.Motivation
These decisions form the cornerstones for your architecture. They are the foundation for many other detailed decisions or implementation rules.

.Form
Keep the explanations of such key decisions short.

Motivate what was decided and why it was decided that way,
based upon problem statement, quality goals and key constraints.
Refer to details in the following sections.

**

=== Technology decisions

To develop the app we will use the following technologies:

* JavaScript is the main programming language.
* ReactJS, a JavaScript library that streamlines the development of graphical interfaces for web applications, it is used to build the user interface.
* Docker Compose to deploy all the microservices.
* GitHub: Platform offering remote repository services for project development, task management, and version control.
* WikiData API to obtain question and answer information.
* ExpressJS to build the backend.

We chose these technologies because they were already being used in the project we based our work on.
This allowed us to build upon an existing foundation, facilitating development and ensuring compatibility while leveraging JavaScript’s agility and ReactJS’s efficiency in building user interfaces.
=== Implementation design
==== Image generation strategy

For the image generation process, we retrieve data from Wikidata using SPARQL queries based on a structured JSON format. This JSON structure defines categories and properties that guide the generation of image prompts.

The JSON structure allows us to select the desired categories for the images, and in the future, specify the style or format. Based on this, we construct a SPARQL query to fetch data from Wikidata and convert it into an image generation request. Here’s an example of a category element in the JSON:

```json
[
    {
        "name": "country",
        "instance": "Q6256",
        "properties": [
            {
                "property": "P18",
                "query": "SELECT ?capital WHERE { ?country wdt:P18 ?capital . FILTER(?country = wd:{x}) }",
                "template": {
                    "es": "Genera una imagen de la capital de x",
                    "en": "Generate an image of the capital of x",
                    "fr": "Générer une image de la capitale de x"
                },
                "category": ["Geography", "Cities"]
            },
            {
                "property": "P18",
                "query": "SELECT ?currency WHERE { ?country wdt:P38 ?currency . FILTER(?country = wd:{x}) }",
                "template": {
                    "es": "Genera una imagen representativa de la moneda de x",
                    "en": "Generate a representative image of the currency of x",
                    "fr": "Générer une image représentative de la devise de x"
                },
                "category": ["Economy"]
            },
            ...
        ],
        ...
    },
    ...
]
```

his structure allows us to dynamically generate SPARQL queries to fetch data from Wikidata, which is then transformed into image generation prompts.

The process consists of the following steps:

Define categories and properties in JSON format.

Generate a SPARQL query based on the selected properties.

Retrieve data from Wikidata using the query.

Convert the data into an image prompt.

Generate the image using an external image generation API.

This approach enables the dynamic creation of images based on specific categories and properties, ensuring a diverse set of visual representations across different topics and languages.

=== Decisions about the top-level decomposition of the system

We decided to use a microservices arquitecture, having different modules for each functionality. 
For example, we will use a microservice to generate the images.


=== Strategies to Achieve Key Quality Goals

The quality goals are explained in more detail in another section.

[options="header",cols="1,2"] 
|=== 
|Quality Goal| Strategies to Achieve It 
|Usability| We will conduct tests with real users to evaluate the app's interface and improve it based on their feedback. 
|Availability| Docker Compose will be used to streamline the app deployment process and prevent issues. Additionally, web hosting will be used to make the app accessible on the internet. 
|Testability| We have created unit and end-to-end (e2e) test suites to ensure the app functions as expected. 
|Performance| We will minimize API calls to maintain quick response times, for instance, by using bulk requests when necessary.
 |===




=== Key Organizational Decisions

Our framework will involve weekly work sessions with meetings scheduled as needed. One meeting will always take place during lab time to assign tasks and make minor decisions.

Additional meetings will be dedicated to more in-depth reviews and major decision-making.

Each task will be tracked as an Issue in GitHub to monitor progress. Moreover, we will use GitHub Projects to streamline the team's workflow. To merge code into the develop branch, we will utilize Pull Requests, which require approval from all team members.