ifndef::imagesdir[:imagesdir: ../images]

[[section-solution-strategy]]
== Solution Strategy

[role="arc42help"]
****
.Contents
A short summary and explanation of the fundamental decisions and solution strategies, that shape system architecture. It includes

* technology decisions
* decisions about the top-level decomposition of the system, e.g. usage of an architectural pattern or design pattern
* decisions on how to achieve key quality goals
* relevant organizational decisions, e.g. selecting a development process or delegating certain tasks to third parties.

.Motivation
These decisions form the cornerstones for your architecture. They are the foundation for many other detailed decisions or implementation rules.

.Form
Keep the explanations of such key decisions short.

Motivate what was decided and why it was decided that way,
based upon problem statement, quality goals and key constraints.
Refer to details in the following sections.
****

=== Technology decisions

To develop the app we will use the following technologies:

* JavaScript is the main programming language.
* ReactJS, a JavaScript library that streamlines the development of graphical interfaces for web applications, it is used to build the user interface.
* Docker Compose to deploy all the microservices.
* GitHub: Platform offering remote repository services for project development, task management, and version control.
* WikiData API to obtain question and answer information.
* ExpressJS and TypeScript to build the backend.

We chose these technologies because they were already being used in the project we based our work on.
This allowed us to build upon an existing foundation, facilitating development and ensuring compatibility while leveraging JavaScript’s agility and ReactJS’s efficiency in building user interfaces.

=== Implementation design

==== Question generation

To generate questions, we use the questions service.

The QuestionDBService is the main orchestrator, responsible for querying
wikidata and turning the API responses into questions.

Every questions belongs to a specific category.
For each category, we define a class that implements the interface
'WikidataRecipe'.

This interface is used by the QuestionDBService to
1) Create a WikidataQueryBuilder, that asks for the specific entities for the
   category
2) Convert the API's response into WikidataEntities, and intern the questions in
   the dababase
3) Generate questions from those entities.

After this process is completed, the service returns a JSON object with the
following structure

```json
[
    {
      "image_url" : "http://commons.wikimedia.org/wiki/Special:FilePath/Erithacus%20rubecula%20with%20cocked%20head.jpg",
      "response" : "Erithacus rubecula",
      "distractors" : ["Invertebrata","Bilateria","Erithacus rubecula"],
      "options" : ["Invertebrata","Bilateria","Erithacus rubecula","Erithacus rubecula"],
      "attrs" : {
          "common_name" : "Petirrojo europeo",
          "taxon_name" : "Erithacus rubecula",
          ...
      }
    },
    ...
]
```

=== Decisions about the top-level decomposition of the system

We decided to use a microservices arquitecture, having different modules for each functionality.
For example, we will use a microservice to generate the images.


=== Strategies to Achieve Key Quality Goals

The quality goals are explained in more detail in another section.

[options="header",cols="1,2"]
|===
|Quality Goal| Strategies to Achieve It
|Usability| We will conduct tests with real users to evaluate the app's interface and improve it based on their feedback.
|Availability| Docker Compose will be used to streamline the app deployment process and prevent issues. Additionally, web hosting will be used to make the app accessible on the internet.
|Testability| We have created unit and end-to-end (e2e) test suites to ensure the app functions as expected.
|Performance| We will minimize API calls to maintain quick response times, for instance, by using bulk requests when necessary.
|===

=== Key Organizational Decisions

Our framework will involve weekly work sessions with meetings scheduled as needed. One meeting will always take place during lab time to assign tasks and make minor decisions.

Additional meetings will be dedicated to more in-depth reviews and major decision-making.

Each task will be tracked as an Issue in GitHub to monitor progress. Moreover, we will use GitHub Projects to streamline the team's workflow. To merge code into the develop branch, we will utilize Pull Requests, which require approval from all team members.
