ifndef::imagesdir[:imagesdir: ../images]

[[section-solution-strategy]]
== Solution Strategy

[role="arc42help"]
**
.Contents
A short summary and explanation of the fundamental decisions and solution strategies, that shape system architecture. It includes

* technology decisions
* decisions about the top-level decomposition of the system, e.g. usage of an architectural pattern or design pattern
* decisions on how to achieve key quality goals
* relevant organizational decisions, e.g. selecting a development process or delegating certain tasks to third parties.

.Motivation
These decisions form the cornerstones for your architecture. They are the foundation for many other detailed decisions or implementation rules.

.Form
Keep the explanations of such key decisions short.

Motivate what was decided and why it was decided that way,
based upon problem statement, quality goals and key constraints.
Refer to details in the following sections.


.Further Information

See https://docs.arc42.org/section-4/[Solution Strategy] in the arc42 documentation.

**

=== Technology decisions

To develop the app we will use the following technologies:

* JavaScript is the main programming language.
* ReactJS, a JavaScript library that streamlines the development of graphical interfaces for web applications, it is used to build the user interface.
* Docker Compose to deploy all the microservices.
* GitHub: Platform offering remote repository services for project development, task management, and version control.
* WikiData API to obtain question and answer information.
* ExpressJS to build the backend.

We chose these technologies because they were already being used in the project we based our work on.
This allowed us to build upon an existing foundation, facilitating development and ensuring compatibility while leveraging JavaScript’s agility and ReactJS’s efficiency in building user interfaces.
=== Implementation design
==== Image generation strategy

==== Question service functionality


=== Decisions about the top-level decomposition of the system

We decided to use a microservices arquitecture, having different modules for each functionality. 
For example, we will use a microservice to generate the questions.

=== Decisions on how to achieve key quality goals

Quality goals are explained in detail in point 10.

[options="header",cols="1,2"]
|===
|Quality goal| Decisions to achieve it.
|Usability| We are going to use real users to test the app interface and improve it according to their feedback.
|Availability| Docker Compose will be helpful to avoid problems with the deploy of the app. In addition we will use web hosting to expose it to the internet.
|Testability| We created unit and e2e (integration) test set to test the application
|Performance| We will use the minimum required calls to the APIs to mantain the minimum time response, for example, with bulk requests.
|===

=== Relevant organizational decisions

Our framework will be based on working every week with meetings when necessary, one will be held always during lab time in order to assign tasks and make minor decisions.
On the other hand, further meetings will be intended for more thorough reviews as well as more significant decisions.

Each assigned task will be created as an Issue in GitHub to track the progress done. In addition, we are going to use GitHub Projects to organize the workflow of the team.
To merge the code to the develop branch we are going to use Pull Requests in order to be approved by every person of the team.