#!/bin/sh

#
# A git hook script to find and fix trailing whitespace
# in your commits. Bypass it with the --no-verify option
# to git-commit
# Ref - http://is.gd/PerowD
#

if ! git rev-parse --verify HEAD >/dev/null 2>&1
then
    exit 0
fi

files=$(git diff-index --check HEAD -- | sed '/^[+-]/d' | sed 's/:[0-9]*:.*//g' | uniq)

for FILE in $files; do
	(sed -i 's/[[:space:]]*$//' "$FILE" > /dev/null 2>&1 || sed -i '' -E 's/[[:space:]]*$//' "$FILE")
	git add "$FILE"
	echo "NOTE: removed trailing whitespace from $FILE"
done
